defaults:
  - model: tiny
  - _self_

test:
  experiment_name: liifa
  logdir: /Users/ignacio.scarinci/Dataset/total_liifa
  data_dir: /Users/ignacio.scarinci/Dataset/total_liifa
  json_list: /Users/ignacio.scarinci/Dataset/total_liifa/dataset.json
  weight: /Users/ignacio.scarinci/Doctorado/SAM-2p5D/training/checkpoint/model_best.pt
  use_amp: True
  tf32: True
  data_loader_workers: 1
  point_prompt: True
  bbox_prompt: False
  point_pos: 3
  point_neg: 1
  roi_z_iter: 9

hydra:
  run:
    dir: /Users/ignacio.scarinci/Doctorado/SAM-2p5D/training/runs/${test.experiment_name}/test

