defaults:
  - model: tiny
  - _self_

data:
  data_dir: /home/iscarinci/total_liifa
  json_list: /home/iscarinci/total_liifa/dataset.json
  splitval: 0.1
  a_min: -1024
  a_max: 1024
  b_min: 0
  b_max: 1

optimizer:
  optim_name: AdamW
  optim_lr: 0.0004
  momentum: 0
  reg_weight: 0.1
  scheduler: cosine
  t0: 20
  tmult: 1
  e_min: 0.000001


trainer:
  experiment_name: ???
  seed: 5344
  max_epochs: 40
  batch_size: 1
  logdir: ../runs/${trainer.experiment_name}/
  snapshot_path: ../runs/${trainer.experiment_name}/snapshot
  use_amp: True
  tf32: True
  save_every: 2
  data_loader_workers: 8
  point_prompt: True
  bbox_prompt: True
  point_pos: None
  point_neg: None
  iterative_training_warm_up_epoch: 20
  num_patch: 24
  num_prompt: 32
  clip: -1
  distributed: True
  skip_bk: True
  max_points: 9
  roi_z_iter: 9
  num_iterative_step: 11
  no_more_points_for_cp_only: False
  num_patch_val: 30
  val_every: 2
  save_checkpoint: True

hydra:
  run:
    dir: ../runs/${trainer.experiment_name}

